# Generated by Django 4.0 on 2022-01-30 16:05

import apps.core.storage_backends
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(storage=apps.core.storage_backends.PrivateMediaStorage(), upload_to='',
                                          verbose_name='File Data')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
