# Generated by Django 4.0 on 2022-01-23 15:48

import apps.core.storage_backends
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(max_length=20971520, storage=apps.core.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='File Data'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
