# Generated by Django 4.0 on 2022-06-19 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=32, verbose_name='Bad word text', unique=True)),
            ],
            options={
                'verbose_name': 'Запрещенное сочетание букв',
                'verbose_name_plural': 'Запрещенные сочетания букв',
            },
        ),
    ]
