# Generated by Django 4.0 on 2022-04-09 00:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0004_alter_telegrammailing_keyboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='Preference Title')),
                ('default', models.SmallIntegerField(verbose_name='Preference Default Value')),
                ('max_value', models.SmallIntegerField(verbose_name='Preference Max Value')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(verbose_name='Preference Enabled')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Preference Value')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preference.preference', verbose_name='Preference')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='telegram.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Пользовательская настройка',
                'verbose_name_plural': 'Пользовательские настройки',
                'unique_together': {('preference', 'telegram_user')},
            },
        ),
    ]
