# Generated by Django 4.0 on 2022-04-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_create_permission_remind_in_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='default',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Preference Default Value'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='max_value',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Preference Max Value'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Preference Value'),
        ),
    ]
