# Generated by Django 4.0 on 2022-03-13 11:05

from django.db import migrations

from apps.preference.constants import NOTIFY_ABOUT_NEW_SCHEDULE


def create_preference_notify_about_new_schedule(apps, schema_editor):
    Preference = apps.get_model('preference', 'Preference')

    Preference.objects.create(slug=NOTIFY_ABOUT_NEW_SCHEDULE)


def create_user_preference_notify_about_new_schedule(apps, schema_editor):
    Preference = apps.get_model('preference', 'Preference')
    UserPreference = apps.get_model('preference', 'UserPreference')
    TelegramUser = apps.get_model('telegram', 'TelegramUser')

    preference = Preference.objects.get(slug=NOTIFY_ABOUT_NEW_SCHEDULE)
    user_preferences = []
    for telegram_user in TelegramUser.objects.all():
        user_preferences.append(
            UserPreference(preference=preference, telegram_user=telegram_user, enabled=True, value=preference.default)
        )

    UserPreference.objects.bulk_create(user_preferences)


class Migration(migrations.Migration):
    dependencies = [
        ('preference', '0003_alter_preference_default_alter_preference_max_value'),
    ]

    operations = [
        migrations.RunPython(code=create_preference_notify_about_new_schedule),
        migrations.RunPython(code=create_user_preference_notify_about_new_schedule),
    ]
