# Generated by Django 4.0 on 2022-02-06 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s3', '0001_initial'),
        ('mospolytech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='Lesson Title')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mospolytech.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='LessonRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, verbose_name='Lesson Room Number')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='LessonTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=32, verbose_name='Lesson Teacher')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=16, verbose_name='Lesson Type')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятия',
            },
        ),
        migrations.CreateModel(
            name='ScheduledLessonNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='Lesson DateTime')),
                ('text', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Lesson Note Text')),
                ('files', models.ManyToManyField(related_name='scheduled_lesson_notes', to='s3.File', verbose_name='Lesson Note Files')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Заметка к запланированному занятию',
                'verbose_name_plural': 'Заметки к запланированным занятиям',
            },
        ),
        migrations.CreateModel(
            name='ScheduledLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(verbose_name='Lesson DateTime')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Запланированное занятие',
                'verbose_name_plural': 'Запланированные занятия',
            },
        ),
        migrations.CreateModel(
            name='LessonPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Lesson Place Title')),
                ('link', models.CharField(blank=True, max_length=128, null=True, verbose_name='Lesson Place Link')),
                ('rooms', models.ManyToManyField(related_name='lessons', to='schedule.LessonRoom', verbose_name='Lesson Rooms')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lessonplace', verbose_name='Lesson Place'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(related_name='lessons', to='schedule.LessonTeacher', verbose_name='Lesson Teachers'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lessontype', verbose_name='Lesson Type'),
        ),
    ]
