# Generated by Django 4.0 on 2022-02-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_lessonteacher_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledlessonnote',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='scheduledlessonnote',
            name='lesson',
        ),
        migrations.AddField(
            model_name='scheduledlessonnote',
            name='scheduled_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.scheduledlesson', verbose_name='Scheduled Lesson'),
        ),
    ]
