# Generated by Django 4.0 on 2022-01-24 20:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_remove_file_title_alter_file_data_alter_file_id'),
        ('schedule', '0002_alter_lesson_id_alter_lessonplace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lessonplace', verbose_name='Lesson Place'),
        ),
        migrations.CreateModel(
            name='ScheduledLessonNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Scheduled Lesson Note Text')),
                ('files', models.ManyToManyField(related_name='scheduled_lesson_notes', to='s3.File', verbose_name='Scheduled Lesson Note Files')),
                ('scheduled_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduledlesson', verbose_name='Scheduled Lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
