# Generated by Django 4.0 on 2022-02-20 11:14

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ScheduledLessonNote = apps.get_model('schedule', 'ScheduledLessonNote')
    ScheduledLessonNote.objects.filter(text__isnull=True).update(text='')


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0003_remove_scheduledlessonnote_datetime_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='scheduledlessonnote',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Lesson Note Text'),
        ),
    ]
