# Generated by Django 4.0 on 2022-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_scheduledlessonnote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplace',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Lesson Place Title'),
        ),
    ]
