# Generated by Django 4.0 on 2022-03-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
        ('schedule', '0005_alter_lessonplace_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlessonnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to='telegram.telegramuser', verbose_name='Created by'),
            preserve_default=False,
        ),
    ]
