# Generated by Django 4.0 on 2022-04-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_lessontype_options_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledlessonnote',
            name='scheduled_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.scheduledlesson', verbose_name='Scheduled Lesson'),
        ),
    ]
