# Generated by Django 4.0 on 2022-04-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_scheduledlessonnote_scheduled_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplace',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Lesson Place Title'),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='number',
            field=models.CharField(max_length=32, verbose_name='Lesson Room Number'),
        ),
        migrations.AlterField(
            model_name='lessonteacher',
            name='full_name',
            field=models.CharField(max_length=64, verbose_name='Lesson Teacher'),
        ),
    ]
