# Generated by Django 4.0 on 2022-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
        ('schedule', '0011_alter_scheduledlessonnotification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplace',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='schedule.LessonRoom', verbose_name='Lesson Rooms'),
        ),
        migrations.AlterField(
            model_name='scheduledlessonnote',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='scheduled_lesson_notes', to='s3.File', verbose_name='Lesson Note Files'),
        ),
    ]
