# Generated by Django 4.0 on 2021-12-31 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, verbose_name='Group Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MospolytechUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=32, unique=True, verbose_name='Mospolytech Login')),
                ('password', models.CharField(max_length=32, verbose_name='Mospolytech Password')),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(to='account.Group', verbose_name='Groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.mospolytechuser', verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.group', verbose_name='Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.mospolytechuser', verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
