# Generated by Django 4.0 on 2022-01-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mospolytechuser',
            name='cached_token',
            field=models.TextField(default=11, verbose_name='Cached Mospolytech Token'),
            preserve_default=False,
        ),
    ]
