# Generated by Django 4.0 on 2021-12-31 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telegram Username')),
                ('full_name', models.CharField(max_length=64, verbose_name='Telegram Full Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
