# Generated by Django 4.0 on 2022-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telegram Username')),
                ('full_name', models.CharField(max_length=64, verbose_name='Telegram Full Name')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
