# Generated by Django 4.0 on 2022-04-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegrambutton_telegramkeyboard_telegrammailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Telegram Admin'),
        ),
    ]
