# Generated by Django 4.0 on 2022-04-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_telegramuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammailing',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='telegram.telegramkeyboard', verbose_name='Mailing Keyboard'),
        ),
    ]
