# Generated by Django 4.0 on 2022-03-13 11:05

from django.db import migrations, models
import encrypted_model_fields.fields


def replace_personal_data_to_user(apps, schema_editor):
    Student = apps.get_model('mospolytech', 'Student')
    Teacher = apps.get_model('mospolytech', 'Teacher')

    for student in Student.objects.all():
        student.user.name = student.personal_data.name
        student.user.surname = student.personal_data.surname
        student.user.patronymic = student.personal_data.patronymic
        student.user.save()

    for teacher in Teacher.objects.all():
        teacher.user.name = teacher.personal_data.name
        teacher.user.surname = teacher.personal_data.surname
        teacher.user.patronymic = teacher.personal_data.patronymic
        teacher.user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('mospolytech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mospolytechuser',
            name='name',
            field=models.CharField(max_length=16, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='mospolytechuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Patronymic'),
        ),
        migrations.AddField(
            model_name='mospolytechuser',
            name='surname',
            field=models.CharField(max_length=16, null=True, verbose_name='Surname'),
        ),
        migrations.RunPython(code=replace_personal_data_to_user),
        migrations.RemoveField(
            model_name='student',
            name='personal_data',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='personal_data',
        ),
        migrations.AlterField(
            model_name='mospolytechuser',
            name='cached_token',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Cached Mospolytech Token'),
        ),
        migrations.DeleteModel(
            name='PersonalData',
        ),
        migrations.AlterField(
            model_name='mospolytechuser',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mospolytechuser',
            name='surname',
            field=models.CharField(max_length=16, verbose_name='Surname'),
        ),
    ]
