# Generated by Django 4.0 on 2022-04-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mospolytech', '0003_alter_student_group_alter_teacher_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mospolytechuser',
            name='login',
            field=models.CharField(max_length=64, verbose_name='Mospolytech Login'),
        ),
        migrations.AlterField(
            model_name='mospolytechuser',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mospolytechuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='mospolytechuser',
            name='surname',
            field=models.CharField(max_length=32, verbose_name='Surname'),
        ),
    ]
